version: '3.8'
services:
  db:
    image: postgres:14
    container_name: db_sample
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
