version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db_sample
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5435}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    image: ghcr.io/${GHCR_USERNAME}/sample_app:latest
    container_name: sample_app
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./ca.pem:/usr/src/app/ca.pem

volumes:
  db_data:

networks:
  backend:
