version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db_sample
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-postgres}'
      POSTGRES_DB: '${DB_NAME:-sampledb}'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    image: ghcr.io/${GHCR_USERNAME}/sample_app:latest
    container_name: sample_app
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      NODE_ENV: staging
      PORT: 3000
      DB_HOST: db
      DB_PORT: '${DB_PORT:-5435}'
      DB_USERNAME: '${DB_USERNAME:-postgres}'
      DB_PASSWORD: '${DB_PASSWORD:-postgres}'
      DB_NAME: '${DB_NAME:-sampledb}'
      JWT_SECRET: '${JWT_SECRET:-your-staging-secret-key}'
    depends_on:
      - db
    networks:
      - backend
    command: ['npm', 'run', 'start:prod']

volumes:
  db_data:

networks:
  backend:
